import type { jsPDF } from 'jspdf';
import { COLOR, CONTENT_WIDTH, FONT, FOOTER_Y, PAGE } from '../theme';
import { formatDate } from '../format';
import { isExpired } from '../status';
import type { QuotationPdfDocument } from '../document';

/**
 * The footer, stamped onto every page once the document is otherwise finished.
 *
 * It has to run last, and that is not a style choice: "Page 2 of 5" needs the
 * total, and jsPDF only knows how many pages there are after the final one has
 * been drawn. So this walks back over the finished document with `setPage`.
 *
 * The validity line is restated here rather than left in the header panel
 * because this document outlives the moment it was generated. It is forwarded,
 * printed and read weeks later, and the reader on page three should not have to
 * turn back to page one to find out whether the price still stands.
 */
export function drawFooters(pdf: jsPDF, doc: QuotationPdfDocument): void {
  const total = pdf.getNumberOfPages();
  const left = PAGE.margin;
  const right = PAGE.margin + CONTENT_WIDTH;
  const reference = doc.reference_no ?? doc.id;

  const validity = !doc.valid_until
    ? 'This quotation does not expire.'
    : isExpired(doc)
      ? `This quotation expired on ${formatDate(doc.valid_until)}.`
      : `Valid until ${formatDate(doc.valid_until)}.`;

  for (let page = 1; page <= total; page += 1) {
    pdf.setPage(page);

    pdf.setDrawColor(...COLOR.line);
    pdf.setLineWidth(0.5);
    pdf.line(left, FOOTER_Y, right, FOOTER_Y);

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(FONT.micro);
    pdf.setTextColor(...COLOR.muted);
    pdf.text(`${reference}  ·  ${validity}`, left, FOOTER_Y + 13);
    pdf.text('Generated by Sinnapi — no signature required.', left, FOOTER_Y + 23);
    pdf.text(`Page ${page} of ${total}`, right, FOOTER_Y + 13, { align: 'right' });
  }
}
